### ISSUE TITLE
Might help - hackage ref instead of GitHub ref hsqml

### ISSUE THREAD

**Issue by kanishka-azimi** [emmanueltouzery/projectpad#1]
You might be able to use extra-deps to refer to hackage instead of having to refer to a commit and clone of hsqml. I haven't tried, just noting if that helps.

**Comment by kanishka-azimi** [comment]
Nevermind, looks like you need a commit specifically, after browsing commit history on stack.yaml.

**Comment by emmanueltouzery** [comment]
Yes, I used to point to a release, but right now you need the latest unreleased hsqml for cabal2 support (needed for ghc8.2/latest stackage).
